---
galaxy_info:
  author: IBM Storage Protect Team
  description: Role for managing IBM Storage Protect HSM Client installation
  company: IBM
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
        - 22.04
  galaxy_tags:
    - storage
    - backup
    - ibm
    - hsm
    - storage_protect

dependencies: []
...
